Update build-kernel-release.yml

diff --git a/.github/workflows/build-kernel-release.yml b/.github/workflows/build-kernel-release.yml
--- a/.github/workflows/build-kernel-release.yml
+++ b/.github/workflows/build-kernel-release.yml
@@ -46,9 +46,76 @@ on:
         default: "gki-android15-6.6"
 
 jobs:
-  build_kernel_release:
-    runs-on: ubuntu-latest
+  build-batch-1: # Non Bazel Builds
+    name: build-batch-1 (${{ matrix.model }}, ${{ matrix.soc }}, ${{ matrix.branch }}, ${{ matrix.manifest }}, ${{ matrix.android_version }}, ${{ matrix.kernel_version }}, ${{ inputs.ksun_branch }})
     strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - model: OP12r
+            soc: kalama
+            branch: oneplus/sm8550
+            manifest: oneplus_12r_v.xml
+            android_version: android13
+            kernel_version: "5.15"
+    runs-on: ubuntu-latest
+    steps:
+      - name: Select Appropriate SusFS Branch
+        id: get-susfs-branch
+        run: |
+          KERNEL_STRING="${{ matrix.android_version }}-${{ matrix.kernel_version }}"
+          
+          case "$KERNEL_STRING" in
+            "android12-5.10")
+              SUSFS_BRANCH="${{ inputs.android12-5_10_susfs_branch }}"
+              ;;
+            "android13-5.10")
+              SUSFS_BRANCH="${{ inputs.android13-5_10_susfs_branch }}"
+              ;;
+            "android13-5.15")
+              SUSFS_BRANCH="${{ inputs.android13-5_15_susfs_branch }}"
+              ;;
+            "android14-5.15")
+              SUSFS_BRANCH="${{ inputs.android14-5_15_susfs_branch }}"
+              ;;
+            "android14-6.1")
+              SUSFS_BRANCH="${{ inputs.android14-6_1_susfs_branch }}"
+              ;;
+            "android15-6.6")
+              SUSFS_BRANCH="${{ inputs.android15-6_6_susfs_branch }}"
+              ;;
+            *)
+              echo "Invalid kernel version or unsupported: $KERNEL_STRING"
+              exit 1
+              ;;
+          esac
+          
+          if [[ -z "$SUSFS_BRANCH" ]]; then
+            SUSFS_BRANCH="gki-${{ matrix.android_version }}-${{ matrix.kernel_version }}"
+          fi
+          
+          echo "susfs_branch=$SUSFS_BRANCH" >> $GITHUB_OUTPUT
+
+      - name: Checkout Code
+        uses: actions/checkout@v3
+
+      - name: Build Kernel
+        uses: ./.github/actions/
+        with:
+          model: ${{ matrix.model }}
+          soc: ${{ matrix.soc }}
+          branch: ${{ matrix.branch }}
+          manifest: ${{ matrix.manifest }}
+          android_version: ${{ matrix.android_version }}
+          kernel_version: ${{ matrix.kernel_version }}
+          ksun_branch: ${{ inputs.ksun_branch }}
+          susfs_branch: ${{ steps.get-susfs-branch.outputs.susfs_branch }}
+
+  build-batch-2:
+    # needs: build-batch-1
+    name: build-batch-2 (${{ matrix.model }}, ${{ matrix.soc }}, ${{ matrix.branch }}, ${{ matrix.manifest }}, ${{ matrix.android_version }}, ${{ matrix.kernel_version }}, ${{ inputs.ksun_branch }})
+    strategy:
+      fail-fast: false
       matrix:
         include:
           - model: OPad2Pro
@@ -63,21 +130,49 @@ jobs:
             manifest: oneplus_pad_3.xml
             android_version: android15
             kernel_version: "6.6"
-
+    runs-on: ubuntu-latest
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0 # Fetch all history for tag generation
-
-      - name: Set up Git
+      - name: Select Appropriate SusFS Branch
+        id: get-susfs-branch
         run: |
-          git config user.name "GitHub Actions"
-          git config user.email "actions@github.com"
+          KERNEL_STRING="${{ matrix.android_version }}-${{ matrix.kernel_version }}"
+          
+          case "$KERNEL_STRING" in
+            "android12-5.10")
+              SUSFS_BRANCH="${{ inputs.android12-5_10_susfs_branch }}"
+              ;;
+            "android13-5.10")
+              SUSFS_BRANCH="${{ inputs.android13-5_10_susfs_branch }}"
+              ;;
+            "android13-5.15")
+              SUSFS_BRANCH="${{ inputs.android13-5_15_susfs_branch }}"
+              ;;
+            "android14-5.15")
+              SUSFS_BRANCH="${{ inputs.android14-5_15_susfs_branch }}"
+              ;;
+            "android14-6.1")
+              SUSFS_BRANCH="${{ inputs.android14-6_1_susfs_branch }}"
+              ;;
+            "android15-6.6")
+              SUSFS_BRANCH="${{ inputs.android15-6_6_susfs_branch }}"
+              ;;
+            *)
+              echo "Invalid kernel version or unsupported: $KERNEL_STRING"
+              exit 1
+              ;;
+          esac
+          
+          if [[ -z "$SUSFS_BRANCH" ]]; then
+            SUSFS_BRANCH="gki-${{ matrix.android_version }}-${{ matrix.kernel_version }}"
+          fi
+          
+          echo "susfs_branch=$SUSFS_BRANCH" >> $GITHUB_OUTPUT
+
+      - name: Checkout Code
+        uses: actions/checkout@v3
 
       - name: Build Kernel
-        id: build_kernel
-        uses: ./OnePlus_KernelSU_SUSFS/ # Updated path based on error
+        uses: ./.github/actions
         with:
           model: ${{ matrix.model }}
           soc: ${{ matrix.soc }}
@@ -85,37 +180,54 @@ jobs:
           manifest: ${{ matrix.manifest }}
           android_version: ${{ matrix.android_version }}
           kernel_version: ${{ matrix.kernel_version }}
-          ksun_branch: ${{ inputs.ksun_branch }} # Sử dụng đầu vào từ workflow_dispatch
-          susfs_branch: ${{ inputs.susfs_branch }} # Sử dụng đầu vào từ workflow_dispatch
+          ksun_branch: ${{ inputs.ksun_branch }}
+          susfs_branch: ${{ steps.get-susfs-branch.outputs.susfs_branch }}
 
-      - name: Set Release Name and Notes
-        run: |
-          RELEASE_NAME="Kernel for ${{ matrix.model }} (${{ matrix.android_version }}-${{ matrix.kernel_version }})"
-          RELEASE_NOTES="This release provides the latest KernelSU Next (v1.0.8) and SUSFS (v1.5.2+) for ${{ matrix.model }} running Android ${{ matrix.android_version }} with kernel version ${{ matrix.kernel_version }}.
-          
-          **KernelSU Next Version:** v1.0.8
-          **SUSFS Version:** v1.5.2+ (Commit: 38e6d6c3)
-          
-          **Disclaimer:** Flashing this kernel will void your warranty, and there is always a risk of bricking your device. Please make sure to back up your data and ensure you understand the risks before proceeding. Proceed at your own risk!
-          
-          **Changes:**
-          - Updated KernelSU Next to v1.0.8
-          - Updated SUSFS to v1.5.2+ (Commit: 38e6d6c3)
-          - General kernel optimizations and bug fixes.
-          "
-          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV
-          echo "RELEASE_NOTES=${RELEASE_NOTES}" >> $GITHUB_ENV
+  trigger-release:
+    needs:
+      - build-batch-1
+      - build-batch-2
+    runs-on: ubuntu-latest
+    if: ${{ inputs.make_release }}
+    env:
+      REPO_OWNER: ${{ github.repository_owner }}
+      REPO_NAME: ${{ github.event.repository.name }}
+      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      RELEASE_NAME: "*TEST BUILD* OnePlus Kernels With KernelSU Next & SUSFS v1.5.8 *TEST BUILD*"
+      RELEASE_NOTES: |
+        This release contains KernelSU Next and SUSFS v1.5.8
+        
+        Module: 
+        -> https://github.com/sidex15/ksu_module_susfs
 
-      - name: Generate and Push Tag
-        if: success() && inputs.make_release == true
+        Non-Official Managers:
+        -> https://github.com/KernelSU-Next/KernelSU-Next
+
+        Features:
+        [+] KernelSU-Next
+        [+] SUSFS v1.5.8
+        [+] Wireguard Support
+        [+] Maphide LineageOS Detections
+        [+] Futile Maphide for jit-zygote-cache Detections
+        [+] Magic Mount Support
+        [+] Ptrace message leak fix for kernels < 5.16
+        [+] Manual Hooks [scope_min_manual_hooks_v1.4]
+        [+] CONFIG_TMPFS_XATTR Support [Mountify Support]
+        [+] BBR v1 Support.
+        [+] HMBIRD scx support for OnePlus 13 & OnePlus Ace 5 Pro.
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Generate and Create New Tag
         run: |
-            BASE_TAG="${{ matrix.model }}-${{ matrix.android_version }}-${{ matrix.kernel_version }}-KSU_Next_v1.0.8-SUSFS_v1.5.2+"
-            LATEST_TAG=$(git tag -l "$BASE_TAG*" | sort -rV | head -n1)
-            
+            BASE_TAG="v1.5.8-r0"
+            LATEST_TAG=$(gh api repos/$REPO_OWNER/$REPO_NAME/tags --jq '.[0].name')
             if [ -z "$LATEST_TAG" ]; then
               LATEST_TAG="$BASE_TAG"
             else
-              LATEST_TAG=$(printf "%s\\n%s\\n" "$LATEST_TAG" "$BASE_TAG" | sort -rV | head -n1)
+              LATEST_TAG=$(printf "%s\n%s\n" "$LATEST_TAG" "$BASE_TAG" | sort -rV | head -n1)
             fi
             NEW_TAG=$(echo "$LATEST_TAG" | awk -F'-r' '{suffix=$2; if (!suffix) suffix=0; suffix++; printf "%s-r%d", $1, suffix}')
             echo "New tag: $NEW_TAG"
@@ -129,7 +241,6 @@ jobs:
           path: ./downloaded-artifacts
 
       - name: Create GitHub Release
-        if: success() && inputs.make_release == true
         uses: actions/create-release@v1
         with:
           tag_name: ${{ env.NEW_TAG }}
@@ -140,7 +251,6 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Upload Release Assets Dynamically
-        if: success() && inputs.make_release == true
         run: |
           for file in ./downloaded-artifacts/kernel-*/*; do
               if [ -d "$file" ]; then
@@ -152,3 +262,8 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NEW_TAG: ${{ env.NEW_TAG }}
+
+      - name: Display Files Uploaded
+        run: |
+          echo "GitHub release created with the following files:"
+          ls ./downloaded-artifacts/**/*
